### ISSUE TITLE
Can't seem to be able to use your own code or even implement this on my project

### ISSUE THREAD

**Issue by affibox** [MacKentoch/reactNativeBeaconExample#1]
I've try in many ways to implement this lib on my RN project but I keep getting this error.
![image](https://cloud.githubusercontent.com/assets/8114543/17569143/f5254512-5f14-11e6-9479-f37baa512653.png)

**Comment by MacKentoch** [comment]
Hi @affibox,

Could you please give me more details on your `package.json` `dependencies` (react, react-native etc...) so that I can figure out what is wrong?

I suspect something in that way but I need more details.

**Comment by affibox** [comment]
"base-64": "^0.1.0",
     "bluebird": "^3.4.1",
     "native-base": "^0.5.4",
     "qs": "^6.2.1",
     "react": "15.2.1",
     "react-native": "0.30.0",
     "react-native-beacons-android": "^1.3.1",
     "react-native-drawer": "^2.2.6",
     "react-native-material-design": "^0.3.7",
     "react-native-router-flux": "^3.32.0",
     "react-native-swipe-cards": "0.0.7"

**Comment by MacKentoch** [comment]
@affibox  Alright this issues is `due to RN 0.29+`.
`rnpm` is now integrated into react native does no more have the same behaviors.

> Thank you for having submitted this issue I was not aware of that before!

**So since RN 0.29+:**
- **no more use `rnpm link`**
   - **if too late**, so follow [react-native-beacons-android#issuecomment-233583330](https://github.com/mmazzarolo/react-native-beacons-android/issues/14#issuecomment-233583330) to **fix it** (*I tested this fix it works*)
- but use `react-native link` (*you won't have to fix with that*)

Now you have also an answer for [react-native-beacons-android#18](https://github.com/mmazzarolo/react-native-beacons-android/issues/18#issuecomment-238991886) so that I save a bit time to @mmazzarolo (Hi btw!)

**Comment by affibox** [comment]
I did that but It throws another error

**Comment by affibox** [comment]
Let me try to uninstall the reinstall and see what happens

**Comment by affibox** [comment]
Like i said, an ERROR occurs when I run 'react-native link'
------------------
C:\Users\jcbar\Desktop\affibox\reactnative\RuralKing>react-native link
rnpm-link info Android module react-native-beacons-android is already linked
rnpm-link info Linking assets to ios project
rnpm-link ERR! It seems something went wrong while linking. Error: Expected "/* Begin ", "/* End ", "\"" or [A-Za-z0-9_.] but "<" found.
Please file an issue here: https://github.com/rnpm/rnpm/issues

C:\Users\jcbar\Desktop\affibox\reactnative\RuralKing\node_modules\promise\lib\done.js:10
      throw err;
      ^
 SyntaxError: Expected "/* Begin ", "/* End ", "\"" or [A-Za-z0-9_.] but "<" found.

C:\Users\jcbar\Desktop\affibox\reactnative\RuralKing>

**Comment by affibox** [comment]
Your suggestion did not worked at all. @MacKentoch 
"@affibox Alright this issues is due to RN 0.29+.
rnpm is now integrated into react native does no more have the same behaviors.

Thank you for having submitted this issue I was not aware of that before!
So since RN 0.29+:

no more use rnpm link
if too late, so follow react-native-beacons-android#issuecomment-233583330 to fix it (I tested this fix it works)
but use react-native link (you won't have to fix with that)
Now you have also an answer for react-native-beacons-android#18 so that I save a bit time to @mmazzarolo (Hi btw!)"
